export const themeOptions = {
  system: { name: 'System', emoji: '💻' },
  light: { name: 'Light', emoji: '☀️' },
  dark: { name: 'Dark', emoji: '🌙' },
  phoenix: { name: 'Phoenix', emoji: '🦅' },
  seaGreen: { name: 'Sea Green', emoji: '🐢' },
  auroraGlow: { name: 'Aurora Glow', emoji: '🌠' },
  crimsonEmber: { name: 'Crimson Ember', emoji: '🔥' },
  slateStorm: { name: 'Slate Storm', emoji: '⛈️' },
  classicSlate: { name: 'Classic Slate', emoji: '🪨' },
  classicWheat: { name: 'Classic Wheat', emoji: '🌾' },
  classicTeal: { name: 'Classic Teal', emoji: '🦚' },
  classicSpruce: { name: 'Classic Spruce', emoji: '🌲' },
  classicStorm: { name: 'Classic Storm', emoji: '⚡' },
  rose: { name: 'Rose', emoji: '🌹' },
  pumpkin: { name: 'Pumpkin', emoji: '🎃' },
  marine: { name: 'Marine', emoji: '⚓' },
  rainyDay: { name: 'Rainy Day', emoji: '🌧️' },
  eggplant: { name: 'Eggplant', emoji: '🍆' },
  plum: { name: 'Plum', emoji: '💜' },
  redBlueWhite: { name: 'Red Blue White', emoji: '🇺🇸' },
  maple: { name: 'Maple', emoji: '🍁' },
  lilac: { name: 'Lilac', emoji: '🌸' },
  desert: { name: 'Desert', emoji: '🏜️' },
  brick: { name: 'Brick', emoji: '🧱' },
  sunset: { name: 'Sunset', emoji: '🌇' },
  forest: { name: 'Forest', emoji: '🌳' },
  neon: { name: 'Neon', emoji: '💡' }
} as const;
